### ISSUE TITLE
Problem updating RCDB

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/rcdb#69]
I'm having trouble updating gluondb1 from gluon119.  Can you confirm which release should work?

Traceback (most recent call last):
  File "update_epics_one.py", line 120, in <module>
    db = rcdb.RCDBProvider("mysql://rcdb:%s@gluondb1/rcdb"%sys.argv[1])
  File "/group/halld/Users/sdobbs/rcdb/python/rcdb/provider.py", line 57, in __init__
    self.connect(connection_string, check_version)
  File "/group/halld/Users/sdobbs/rcdb/python/rcdb/provider.py", line 112, in connect
    raise rcdb.errors.SqlSchemaVersionError(message)
rcdb.errors.SqlSchemaVersionError: SQL schema version doesn't match. Probably RCDB is connecting with wrong, empty or older/newer DB

**Comment by sdobbs** [comment]
This works now, it was some obscure parsing problem...
